create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(trim(content)) between 1 and 500),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

alter table public.messages enable row level security;

drop policy if exists "Public can read messages" on public.messages;
create policy "Public can read messages"
  on public.messages
  for select
  to anon
  using (true);

drop policy if exists "Public can insert messages" on public.messages;
create policy "Public can insert messages"
  on public.messages
  for insert
  to anon
  with check (true);

drop policy if exists "Public can delete messages" on public.messages;
create policy "Public can delete messages"
  on public.messages
  for delete
  to anon
  using (true);

comment on table public.messages is
  'Public messageboard entries managed through Next.js API routes.';